export const ClientToServerEvents = {
  authHello: "auth:hello",
  presenceSet: "presence:set",
  roomCreate: "room:create",
  roomJoin: "room:join",
  roomLeave: "room:leave",
  callDirectInvite: "call:direct:invite",
  callDirectAccept: "call:direct:accept",
  callDirectDecline: "call:direct:decline",
  webrtcOffer: "webrtc:offer",
  webrtcAnswer: "webrtc:answer",
  webrtcIce: "webrtc:ice",
  roomHostMute: "room:host:mute",
  roomHostKick: "room:host:kick",
  roomHostLock: "room:host:lock",
  userNicknameSet: "user:nickname:set",
  userSearch: "user:search",
  friendsRequestSend: "friends:request:send",
  friendsRequestRespond: "friends:request:respond",
  friendsList: "friends:list",
  friendsRemove: "friends:remove",
  dmThreadGetOrCreate: "dm:thread:getOrCreate",
  dmThreadList: "dm:thread:list",
  dmHistory: "dm:history",
  dmSend: "dm:send",
  dmTyping: "dm:typing",
  roomChatHistory: "room:chat:history",
  roomChatSend: "room:chat:send",
  msgEdit: "msg:edit",
  msgDelete: "msg:delete",
  msgReact: "msg:react",
  notificationsRead: "notifications:read"
} as const;

export const ServerToClientEvents = {
  authOk: "auth:ok",
  presenceList: "presence:list",
  roomList: "room:list",
  roomJoined: "room:joined",
  roomParticipantJoined: "room:participant:joined",
  roomParticipantLeft: "room:participant:left",
  callDirectIncoming: "call:direct:incoming",
  callDirectState: "call:direct:state",
  webrtcOffer: "webrtc:offer",
  webrtcAnswer: "webrtc:answer",
  webrtcIce: "webrtc:ice",
  webrtcSignalError: "webrtc:signal:error",
  roomHostAction: "room:host:action",
  userNicknameOk: "user:nickname:ok",
  userSearchResult: "user:search:result",
  friendsRequests: "friends:requests",
  friendsList: "friends:list",
  friendsRequestUpdate: "friends:request:update",
  dmThreadList: "dm:thread:list",
  dmMessageNew: "dm:message:new",
  dmHistory: "dm:history",
  dmSendAck: "dm:send:ack",
  dmTyping: "dm:typing",
  roomChatMessage: "room:chat:message",
  roomChatHistory: "room:chat:history",
  roomChatSendAck: "room:chat:send:ack",
  msgUpdated: "msg:updated",
  msgReactionUpdate: "msg:reaction:update",
  notificationList: "notification:list",
  notificationNew: "notification:new",
  error: "error"
} as const;

export type ClientEventName = (typeof ClientToServerEvents)[keyof typeof ClientToServerEvents];
export type ServerEventName = (typeof ServerToClientEvents)[keyof typeof ServerToClientEvents];
